language: generic

os: linux
dist: bionic

services:
  - docker

before_install:
  - ./scripts/install_yq.sh
  - ./scripts/install_jq.sh

script:
  - ./scripts/hub_build.sh config/my_appsody_stacks.yaml
  - ./scripts/list_artifacts.sh
    
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: assets/**/*
  file_glob: true
  on:
    tags: true
    repo: garypicher/mystackhub
